__default__:
    partition: short.q
    job-name: LRRtransfer.{rule}
    output: LRRtransfer.{rule}.err
    error:  LRRtransfer.{rule}.out

genePrediction:
    partition: short.q
    job-name: LRRtransfer.{rule}.{wildcards.split_id}
    output: LRRtransfer.{rule}.{wildcards.split_id}.err
    error:  LRRtransfer.{rule}.{wildcards.split_id}.out
