cluster: "sbatch -p agap_normal -p {cluster.partition} -o {cluster.output} -e {cluster.error}"
restart-times: 3
local-cores: 1
latency-wait: 60
use-conda: True
use-singularity: True
use-envmodules: True
jobs: 200
keep-going: True
rerun-incomplete: True
#shadow-prefix: /lustre/gottinc/SNAKEMAKE/
printshellcmds: True
