### GENERAL VARIABLES ###

# Mandatory files
target_genome:     "/lustre/gottinc/SNAKEMAKE/example/Punctata_chr1.fasta"
ref_genome:        "/lustre/gottinc/SNAKEMAKE/example/Nipponbare_chr1.fasta"
ref_gff:           "/lustre/gottinc/SNAKEMAKE/example/Nipponbare_LRR-CR_chr1.gff"
ref_locus_info:    "/lustre/gottinc/SNAKEMAKE/example/Info_locus_Nipponbare.txt"

# optional folder containing a prebuild LRROME
lrrome:            ""
OUTPUTS_DIRNAME: "/lustre/gottinc/SNAKEMAKE/LRR_TRANSFERT_OUTPUTS"
